admins:
  - '.*'

cronSchedule: '0 2 * * *'

institutions: []

allTagGroups:
  Rent:
    - rent
  Groceries:
    - groceries
  Toys:
    - toys
  Bills:
    - gym
    - internet bill
    - electricity bill
    - gas bill
    - water bill
    - netflix
    - charity
    - phone bill
    - life insurance
    - health insurance
    - school
  Health:
    - pharmacy
    - appointments
    - dentist
  Clothing:
    - clothes
  Car:
    - fuel
    - car repairs
    - car wash
  Gifts:
    - gifts
  Go out:
    - go out
  Takeaway:
    - takeaway
  Home:
    - home
  Electronics:
    - electronics
    - games

ungroupedTags:
  - parties

tagPatterns: []

budget:
  pushNotifications:
    # cronSchedule defaults to '30 9 */5 * *' (every 5 days at 9:30am)
    openUrl: http://expenses.diogocastro.com/#/budget
  # The budget calculations will include any txs that have one of the tags listed below
  # OR are from one of the accounts listed below.
  #
  # Txs that match an account name but not any of the listed tags will be included in the "Other" tag group.
  tagGroups:
    - name: Groceries
      tags: [groceries]
      limit: 650
    - name: Go out
      tags: [go out]
      limit: 100
    - name: Clothes
      tags: [clothes]
      limit: 100
    - name: Other
      limit: 200
      tags:
        - pharmacy
        - home
        - fuel
  includeAllTxsFromAccounts: []

# Transactions with these tags are marked as "not an expense".
notExpenses: []
