admins:
  - diogo.filipe.acastro
  - sonia.d.c.barbosa
  - test

cronSchedule: '0 2 * * *'

accountInfos: []

allTagGroups:
  Rent:
    - rent
  Groceries:
    - groceries
  Toys:
    - toys
  Bills:
    - gym
    - internet bill
    - electricity bill
    - gas bill
    - water bill
    - netflix
    - charity
    - phone bill
    - life insurance
    - health insurance
    - school
  Health:
    - pharmacy
    - appointments
    - dentist
  Clothing:
    - clothes
  Car:
    - fuel
    - car repairs
    - car wash
  Gifts:
    - gifts
  Go out:
    - go out
  Takeaway:
    - takeaway
  Home:
    - home
  Electronics:
    - electronics
    - games

categoryPatterns: []

notExpenses: []
