admins:
  - '.*'

cronSchedule: '0 2 * * *'

institutions: []

allTagGroups:
  Rent:
    - rent
  Groceries:
    - groceries
  Toys:
    - toys
  Bills:
    - gym
    - internet bill
    - electricity bill
    - gas bill
    - water bill
    - netflix
    - charity
    - phone bill
    - life insurance
    - health insurance
    - school
  Health:
    - pharmacy
    - appointments
    - dentist
  Clothing:
    - clothes
  Car:
    - fuel
    - car repairs
    - car wash
  Gifts:
    - gifts
  Go out:
    - go out
  Takeaway:
    - takeaway
  Home:
    - home
  Electronics:
    - electronics
    - games

ungroupedTags:
  - parties

tagPatterns: []

budget:
  tagGroups:
    - name: Groceries
      tags: [groceries]
      limit: 650
    - name: Go out
      tags: [go out]
      limit: 100
    - name: Other
      limit: 100
      tags:
        - casa
        - eletronica
        - jogos
  # In addition to the tags listed above, also include all txs from these accounts in the budget calculations.
  includeAllTxsFromAccounts: []

# Transactions with these tags are marked as "not an expense".
notExpenses: []
